import { Router, type IRouter } from "express";
import healthRouter from "./health";
import unidadesRouter from "./unidades";
import usuariosRouter from "./usuarios";
import pacientesRouter from "./pacientes";
import anamneseRouter from "./anamnese";
import motorClinicoRouter from "./motorClinico";
import blocosRouter from "./blocos";
import protocolosRouter from "./protocolos";
import filasRouter from "./filas";
import followupRouter from "./followup";
import financeiroRouter from "./financeiro";
import dashboardRouter from "./dashboard";
import fluxosRouter from "./fluxos";
import catalogoRouter from "./catalogo";
import questionarioPacienteRouter from "./questionarioPaciente";
import pedidosExameRouter from "./pedidosExame";
import substanciasRouter from "./substancias";
import sessoesRouter from "./sessoes";
import rasRouter from "./rasRoute";
import codigosSemanticosRouter from "./codigosSemanticos";
import googleCalendarRouter from "./googleCalendar";
import googleDriveRouter from "./googleDrive";
import googleGmailRouter from "./googleGmail";
import avaliacaoEnfermagemRouter from "./avaliacaoEnfermagem";
import taskCardsRouter from "./taskCards";
import rasEvolutivoRouter from "./rasEvolutivo";
import avaliacoesClienteRouter from "./avaliacoesCliente";
import portalClienteRouter from "./portalCliente";

const router: IRouter = Router();

router.use(healthRouter);
router.use(unidadesRouter);
router.use(usuariosRouter);
router.use(pacientesRouter);
router.use(anamneseRouter);
router.use(motorClinicoRouter);
router.use(blocosRouter);
router.use(protocolosRouter);
router.use(filasRouter);
router.use(followupRouter);
router.use(financeiroRouter);
router.use(dashboardRouter);
router.use(fluxosRouter);
router.use("/catalogo", catalogoRouter);
router.use(questionarioPacienteRouter);
router.use("/pedidos-exame", pedidosExameRouter);
router.use(substanciasRouter);
router.use(sessoesRouter);
router.use(rasRouter);
router.use(codigosSemanticosRouter);
router.use(googleCalendarRouter);
router.use(googleDriveRouter);
router.use(googleGmailRouter);
router.use(avaliacaoEnfermagemRouter);
router.use(taskCardsRouter);
router.use(rasEvolutivoRouter);
router.use(avaliacoesClienteRouter);
router.use(portalClienteRouter);

export default router;
