import { Router, type IRouter } from "express";
import healthRouter from "./health";
import unidadesRouter from "./unidades";
import usuariosRouter from "./usuarios";
import pacientesRouter from "./pacientes";
import anamneseRouter from "./anamnese";
import motorClinicoRouter from "./motorClinico";
import blocosRouter from "./blocos";
import protocolosRouter from "./protocolos";
import filasRouter from "./filas";
import followupRouter from "./followup";
import financeiroRouter from "./financeiro";
import dashboardRouter from "./dashboard";
import fluxosRouter from "./fluxos";
import catalogoRouter from "./catalogo";
import questionarioPacienteRouter from "./questionarioPaciente";
import pedidosExameRouter from "./pedidosExame";
import substanciasRouter from "./substancias";
import sessoesRouter from "./sessoes";
import rasRouter from "./rasRoute";
import codigosSemanticosRouter from "./codigosSemanticos";
import googleCalendarRouter from "./googleCalendar";
import googleDriveRouter from "./googleDrive";
import googleGmailRouter from "./googleGmail";
import avaliacaoEnfermagemRouter from "./avaliacaoEnfermagem";
import taskCardsRouter from "./taskCards";
import rasEvolutivoRouter from "./rasEvolutivo";
import avaliacoesClienteRouter from "./avaliacoesCliente";
import portalClienteRouter from "./portalCliente";
import cavaloClinicalRouter from "./cavaloClinical";
import soberaniaRouter from "./soberania";
import auditoriaCascataRouter from "./auditoriaCascata";
import alertasRouter from "./alertas";
import governancaRouter from "./governanca";
import examesInteligenteRouter from "./examesInteligente";
import monitoramentoPacienteRouter from "./monitoramentoPaciente";
import alertaPacienteRouter from "./alertaPaciente";
import direcaoExameRouter from "./direcaoExame";
import formulaBlendRouter from "./formulaBlend";
import backupDriveRouter from "./backupDrive";
import whatsappRouter from "./whatsapp";

const router: IRouter = Router();

router.use(healthRouter);
router.use(unidadesRouter);
router.use(usuariosRouter);
router.use(pacientesRouter);
router.use(anamneseRouter);
router.use(motorClinicoRouter);
router.use(blocosRouter);
router.use(protocolosRouter);
router.use(filasRouter);
router.use(followupRouter);
router.use(financeiroRouter);
router.use(dashboardRouter);
router.use(fluxosRouter);
router.use("/catalogo", catalogoRouter);
router.use(questionarioPacienteRouter);
router.use("/pedidos-exame", pedidosExameRouter);
router.use(substanciasRouter);
router.use(sessoesRouter);
router.use(rasRouter);
router.use(codigosSemanticosRouter);
router.use(googleCalendarRouter);
router.use(googleDriveRouter);
router.use(googleGmailRouter);
router.use(avaliacaoEnfermagemRouter);
router.use(taskCardsRouter);
router.use(rasEvolutivoRouter);
router.use(avaliacoesClienteRouter);
router.use(portalClienteRouter);
router.use(cavaloClinicalRouter);
router.use(soberaniaRouter);
router.use(auditoriaCascataRouter);
router.use(alertasRouter);
router.use(governancaRouter);
router.use(examesInteligenteRouter);
router.use(monitoramentoPacienteRouter);
router.use(alertaPacienteRouter);
router.use(direcaoExameRouter);
router.use(formulaBlendRouter);
router.use(backupDriveRouter);
router.use(whatsappRouter);

export default router;
