import { Router, type IRouter } from "express";
import healthRouter from "./health";
import unidadesRouter from "./unidades";
import usuariosRouter from "./usuarios";
import pacientesRouter from "./pacientes";
import anamneseRouter from "./anamnese";
import motorClinicoRouter from "./motorClinico";
import blocosRouter from "./blocos";
import protocolosRouter from "./protocolos";
import filasRouter from "./filas";
import followupRouter from "./followup";
import financeiroRouter from "./financeiro";
import dashboardRouter from "./dashboard";
import fluxosRouter from "./fluxos";
import catalogoRouter from "./catalogo";
import questionarioPacienteRouter from "./questionarioPaciente";
import pedidosExameRouter from "./pedidosExame";
import substanciasRouter from "./substancias";
import sessoesRouter from "./sessoes";
import rasRouter from "./rasRoute";
import codigosSemanticosRouter from "./codigosSemanticos";
import googleCalendarRouter from "./googleCalendar";
import googleDriveRouter from "./googleDrive";
import googleGmailRouter from "./googleGmail";
import avaliacaoEnfermagemRouter from "./avaliacaoEnfermagem";
import taskCardsRouter from "./taskCards";
import rasEvolutivoRouter from "./rasEvolutivo";
import avaliacoesClienteRouter from "./avaliacoesCliente";
import portalClienteRouter from "./portalCliente";
import cavaloClinicalRouter from "./cavaloClinical";
import soberaniaRouter from "./soberania";
import auditoriaCascataRouter from "./auditoriaCascata";
import alertasRouter from "./alertas";
import governancaRouter from "./governanca";
import examesInteligenteRouter from "./examesInteligente";
import monitoramentoPacienteRouter from "./monitoramentoPaciente";
import alertaPacienteRouter from "./alertaPaciente";
import direcaoExameRouter from "./direcaoExame";
import formulaBlendRouter from "./formulaBlend";
import backupDriveRouter from "./backupDrive";
import whatsappRouter from "./whatsapp";
import seedSemanticoRouter from "./seedSemantico";
import semanticoRouter from "./semantico";
import segurancaRouter from "./seguranca";
import delegacaoRouter from "./delegacao";
import seedConsultoriaRouter from "./seedConsultoria";
import acompanhamentoRouter from "./acompanhamento";
import comissaoRouter from "./comissao";
import comercialRouter from "./comercial";
import slaRouter from "./sla";
import matrixRouter from "./matrix";
import agendaMotorRouter from "./agenda-motor";
import colaboradoresRouter from "./colaboradores";
import agentesVirtuaisRouter from "./agentesVirtuais";
import rasDistribuirRouter from "./rasDistribuir";
import consultoriasRouter from "./consultoriasRoute";
import contratosRouter from "./contratosRoute";

const router: IRouter = Router();

router.use(healthRouter);
router.use(unidadesRouter);
router.use(usuariosRouter);
router.use(pacientesRouter);
router.use(anamneseRouter);
router.use(motorClinicoRouter);
router.use(blocosRouter);
router.use(protocolosRouter);
router.use(filasRouter);
router.use(followupRouter);
router.use(financeiroRouter);
router.use(dashboardRouter);
router.use(fluxosRouter);
router.use("/catalogo", catalogoRouter);
router.use(questionarioPacienteRouter);
router.use("/pedidos-exame", pedidosExameRouter);
router.use(substanciasRouter);
router.use(sessoesRouter);
router.use(rasRouter);
router.use(codigosSemanticosRouter);
router.use(googleCalendarRouter);
router.use(googleDriveRouter);
router.use(googleGmailRouter);
router.use(avaliacaoEnfermagemRouter);
router.use(taskCardsRouter);
router.use(rasEvolutivoRouter);
router.use(avaliacoesClienteRouter);
router.use(portalClienteRouter);
router.use(cavaloClinicalRouter);
router.use(soberaniaRouter);
router.use(auditoriaCascataRouter);
router.use(alertasRouter);
router.use(governancaRouter);
router.use(examesInteligenteRouter);
router.use(monitoramentoPacienteRouter);
router.use(alertaPacienteRouter);
router.use(direcaoExameRouter);
router.use(formulaBlendRouter);
router.use(backupDriveRouter);
router.use(whatsappRouter);
router.use("/seed-semantico", seedSemanticoRouter);
router.use("/semantico", semanticoRouter);
router.use(segurancaRouter);
router.use("/delegacao", delegacaoRouter);
router.use("/seed-consultoria", seedConsultoriaRouter);
router.use(acompanhamentoRouter);
router.use(comissaoRouter);
router.use(comercialRouter);
router.use(slaRouter);
router.use(matrixRouter);
router.use(agendaMotorRouter);
router.use("/colaboradores", colaboradoresRouter);
router.use("/agentes-virtuais", agentesVirtuaisRouter);
router.use(rasDistribuirRouter);
router.use(consultoriasRouter);
router.use(contratosRouter);

export default router;
