// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/PdfJustificativa.tsx": () => import("../components/mockups/PdfJustificativa.tsx"),
  "./components/mockups/PdfSolicitacao.tsx": () => import("../components/mockups/PdfSolicitacao.tsx")
};
